import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/database";
import type { AgentChainResultPayload } from "@/lib/agents/types";

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = createClient();

    // Get authenticated user
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Get project
    const { data: project, error: projectError } = await supabase
      .from("projects")
      .select("*")
      .eq("id", params.id)
      .eq("user_id", user.id)
      .single();

    if (projectError || !project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    // Get agent outputs
    const chainOutput = project.final_output || project.agent_outputs;
    if (!chainOutput) {
      return NextResponse.json(
        { error: "No code generated yet" },
        { status: 400 }
      );
    }

    // Collect all files
    const files: Record<string, string> = {};

    const output = chainOutput as Partial<AgentChainResultPayload>;

    // Add API routes from Agent 3
    if (output.agent3_output?.api_routes) {
      output.agent3_output.api_routes.forEach((route) => {
        const path = `app/api${route.path}/route.ts`;
        files[path] = route.code;
      });
    }

    // Add database migrations from Agent 3
    if (output.agent3_output?.database_migrations) {
      output.agent3_output.database_migrations.forEach((migration, index) => {
        files[`database/migrations/${String(index + 1).padStart(3, "0")}_migration.sql`] = migration;
      });
    }

    // Add components from Agent 4
    if (output.agent4_output?.components) {
      output.agent4_output.components.forEach((comp) => {
        files[comp.path] = comp.code;
      });
    }

    // Add styles from Agent 4
    if (output.agent4_output?.styles) {
      output.agent4_output.styles.forEach((style) => {
        files[style.path] = style.code;
      });
    }

    // Add integrations from Agent 5
    if (output.agent5_output?.integrations) {
      output.agent5_output.integrations.forEach((integration) => {
        files[`lib/${integration.name}.ts`] = integration.code;
      });
    }

    // Add state management from Agent 5
    if (output.agent5_output?.state_management?.stores) {
      output.agent5_output.state_management.stores.forEach((store) => {
        files[`lib/stores/${store.name}.ts`] = store.code;
      });
    }

    // Add forms from Agent 5
    if (output.agent5_output?.forms) {
      output.agent5_output.forms.forEach((form) => {
        files[form.path] = form.code;
      });
    }

    // Add error handling from Agent 5
    if (output.agent5_output?.error_handling) {
      files["lib/error-handler.ts"] = output.agent5_output.error_handling.global_handler;
      files["components/ErrorBoundary.tsx"] = output.agent5_output.error_handling.error_boundary;
    }

    // Add test files from Agent 6
    if (output.agent6_output?.test_files) {
      output.agent6_output.test_files.forEach((test) => {
        files[test.path] = test.code;
      });
    }

    // Add deployment configs from Agent 7
    if (output.agent7_output?.deployment_config?.config_files) {
      output.agent7_output.deployment_config.config_files.forEach((config) => {
        files[config.name] = config.content;
      });
    }

    // Add package.json
    const dependencies = output.agent2_output?.dependencies || {};
    files["package.json"] = JSON.stringify(
      {
        name: project.name || "generated-project",
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
          lint: "next lint",
          test: "jest",
          "test:e2e": "playwright test",
        },
        dependencies: {
          next: "14.0.0",
          react: "18.2.0",
          "react-dom": "18.2.0",
          ...dependencies,
        },
        devDependencies: {
          "@types/node": "20.0.0",
          "@types/react": "18.2.0",
          "@types/react-dom": "18.2.0",
          typescript: "5.0.0",
          eslint: "8.0.0",
          "eslint-config-next": "14.0.0",
          jest: "29.0.0",
          "@testing-library/react": "14.0.0",
          "@testing-library/jest-dom": "6.0.0",
          "@playwright/test": "1.40.0",
        },
      },
      null,
      2
    );

    // Add README
    files["README.md"] = `# ${project.name || "Generated Project"}

${project.user_prompt}

## Generated by Mr.Promth

This project was automatically generated using AI agent chain.

### Tech Stack

- Next.js 14
- React 18
- TypeScript
- Tailwind CSS
- Supabase

### Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Set up environment variables:
\`\`\`bash
cp .env.example .env.local
\`\`\`

3. Run the development server:
\`\`\`bash
npm run dev
\`\`\`

4. Open [http://localhost:3000](http://localhost:3000) in your browser.

### Deployment

Deploy to Vercel with one click or follow the deployment guide in DEPLOYMENT.md.

### Generated Files

- **API Routes**: ${output.agent3_output?.api_routes?.length || 0} files
- **Components**: ${output.agent4_output?.components?.length || 0} files
- **Tests**: ${output.agent6_output?.test_files?.length || 0} files
- **Total Files**: ${Object.keys(files).length} files

---

Generated on ${new Date().toISOString()}
`;

    // Create a simple text-based archive (in production, use JSZip)
    let archive = "";
    for (const [path, content] of Object.entries(files)) {
      archive += `\n\n=== ${path} ===\n\n${content}`;
    }

    return new NextResponse(archive, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="${project.name || "project"}.txt"`,
      },
    });
  } catch (error) {
    console.error("Download error:", error);
    return NextResponse.json(
      { error: "Failed to generate download" },
      { status: 500 }
    );
  }
}
